function H = secondOrderFuncEndocytosis(a, pm, N, ki, kd, InConst)
% Input is Heaviside with C0 = 1.17e13;
H = @(s1,s2) -a/2.*(a*pm*N./(ki + s1) + a*pm*N./(ki + s2))./...
    (ki + s1 + s2).* ...
    ki./(kd + s1 + s2).* ...
    InConst./(s1).*InConst./(s2);
end