function H = thirdOrderFuncEndocytosis(a, pm, N, ki, kd, InConst)
% Input is Heaviside with C0 = 1.17e13;
H = @(s1,s2,s3) -a/3.* ...
    (-a/2.*(a*pm*N./(ki + s1) + a*pm*N./(ki + s2))./(ki + s1 + s2) + ...
    -a/2.*(a*pm*N./(ki + s1) + a*pm*N./(ki + s3))./(ki + s1 + s3) + ...
    -a/2.*(a*pm*N./(ki + s2) + a*pm*N./(ki + s3))./(ki + s2 + s3))./ ...
        (ki + s1 + s2 + s3).* ...
        ki./(kd + s1 + s2 + s3).* ...
        InConst./(s1).*InConst./(s2).*InConst./(s3);
end