
function dstat_vars_dt = SCALED_DIMLESS_SM_XIP(t, stat_vars  ...
    ,qD, delta_XIP_int, delta_XIP_ext ,k_TF_m  ...
    ,k_TF_f ,delta_tf ,delta_mtf ,alpha_comR,alpha_sigX,kappaB ,kappa_comR ,k_comR ... 
    ,deltaR,  kappaX, k_SigX, deltaSigX,n_sol,v, Ve,kL, deltaEL, ...
     XIP_int_c, ...
     XIP_ext_c, ...
     ComRf_c,   ...
     ComRm_c,   ...
     sigX_c,    ...
     SigX_c,    ...
     E_L_c,     ...
     n_c,       ...
     v_c,       ...
     tc)

    

      % Solving for Bacterial Population Size Normalized
      n = (deval(n_sol,t)./n_c);         % Clarification: evaltuion of n_sol yields non_normalized number; NB! This is probably NOT strictly necessary, so remove 




      % XIP_int_SCALED 
      dstat_vars_dt(1,1) = - qD *   (n.*n_c) * (tc/XIP_int_c) *  ...
      ((stat_vars(1) * XIP_int_c)/( (n.*n_c)*v) - stat_vars(6)*XIP_ext_c) - ...
       delta_XIP_int * tc * stat_vars(1) - ...
       1/( (n.*n_c)*v)  * k_TF_m * tc *  stat_vars(1) * stat_vars(2) * ComRf_c  + ...
       k_TF_f * tc * stat_vars(3) *  ComRm_c; 

       
       % FREE comR_SCALED
       dstat_vars_dt(2,1) =   (n.*n_c) * (tc/ComRf_c)  * alpha_comR * kappaB  +...                           % SigX induced gene expression
                              k_TF_f * (tc/ComRf_c) * stat_vars(3) * ComRm_c  - ...
                              1/( (n.*n_c)*v)  * k_TF_m * tc * XIP_int_c * stat_vars(1) * stat_vars(2) - ...
                              delta_tf * stat_vars(2) * tc  + ...
                               (n.*n_c) * alpha_comR * kappaX * (tc/ComRf_c)* ...
                              (((stat_vars(5)*SigX_c)/( (n.*n_c)*v))/ (k_SigX+((stat_vars(5)*SigX_c)/( (n.*n_c)*v))));   


       % Mature ComR SCALED
       dstat_vars_dt(3,1) =  1/( (n.*n_c)*v)  *  tc/ComRm_c  * k_TF_m * stat_vars(1) * XIP_int_c * stat_vars(2)  * ComRf_c - ...
                              k_TF_f* stat_vars(3) * tc  - ...
                              delta_mtf* stat_vars(3) * tc; 




       % sigX SCALED
       dstat_vars_dt(4,1) =   (n.*n_c) * kappa_comR * (tc/sigX_c) * (((stat_vars(3)*ComRm_c)/( (n.*n_c)*v))/ (k_comR+((stat_vars(3)*ComRm_c)/( (n.*n_c)*v)))) ...
                - deltaR * stat_vars(4) * tc;




       % SigX SCALED
       dstat_vars_dt(5,1) =  (n.*n_c) * kappa_comR * alpha_sigX * (tc/SigX_c)   *   (((stat_vars(3)*ComRm_c)/( (n.*n_c)*v))/ (k_comR+((stat_vars(3)*ComRm_c)/( (n.*n_c)*v)))) ...
                           - deltaSigX * stat_vars(5) * tc; 


       % XIP_ext SCALED
       dstat_vars_dt(6,1) = qD *   (n.*n_c) * 1/(Ve/v_c) * (tc/XIP_ext_c)  * ((XIP_int_c * stat_vars(1))/( (n.*n_c)*v) -  stat_vars(6)*XIP_ext_c) -...
           delta_XIP_ext * stat_vars(6) * tc;


        % Luciferase 
        dstat_vars_dt(7,1) = kL  * (tc/E_L_c) * stat_vars(4) * sigX_c - stat_vars(7) * deltaEL * tc;

end